apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Yeh line saare resources ko automatic is namespace mein daal degi
namespace: stock

# 2. Files ki list (Isme humne namespace ki file bhi jod di hai)
resources:
  - namespace.yaml # Jo sabse pehle banayi thi
  - pv.yaml
  - pvc.yaml
  - db-secret.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - flaskdeployment.yaml
  - flaskservice.yaml

commonLabels:
  app: mysql-stack
